[package]
name = "lua"
version = "5.4.1"
authors = ["B. Howe <37745048+byhowe@users.noreply.github.com>"]
edition = "2018"

[dependencies]
lua-sys = { version = "5.4.1", path = "../lua-sys" }
libc = "0.2"

[features]
default = ["static"]

static = ["lua-sys/static"]
